### ISSUE TITLE
RetroLambda generates wrong method call

### ISSUE THREAD

**Issue by Zardoz89** [orfjackal/retrolambda#100]
On our source code, we call to Apache Commons Colections  2.1.1 **MultiMap.remove** method that have this signature :  ``` MultiMap.remove ( Object key, Object value )  :  Object ``` 
However RetroLambda, changes it by a call to  ``` MultiMap.remove ( Object key, Object value )  :  Boolean ``` , that give us a runtime error :``` java.lang.NoSuchMethodError: org.apache.commons.collections.MultiMap.remove(Ljava/lang/Object;Ljava/lang/Object;)Z```

Using RetroLambda 2.3.0 over Oracle Java 8 , to compile from Java 7 bytecode to Java 6 bytecode.

**Comment by Zardoz89** [comment]
I found more information why RetroLambda get confused. 
On our code, we use a "MultiHashMap" class of Apache Commons Collections, that implements MultiMap interface and extends HashMap class. So, we have ```Object MultiMap.remove ( Object key, Object value )``` colliding with ```boolean HashMap.remove ( Object key, Object value )```

**Comment by orfjackal** [comment]
Thanks for that information. It may prove to be useful in finding the bug.

**Comment by afboteroz** [comment]
The problem with the call is a bug of the Apache Commons Collections with Java8, not of RetroLambda. It appears that the bug is fixed in the v4

> Renamed "V MultiMap#remove(K, V)" to "boolean MultiMap#removeMapping(K, V)" to avoid future conflicts with a default method of the Map interface in Java 8.
[Apache Commons Collections Release Notes](https://commons.apache.org/proper/commons-collections/release_4_0.html)
