### ISSUE TITLE
Default method is causing Abstract Method error on Android

### ISSUE THREAD

**Issue by sriharshachilakapati** [orfjackal/retrolambda#108]
I'm using Retrolambda with a library on Android, and also the app which uses that android library. The library has the following interface.

``` java
public interface IDisplayDevice
{
    // [snip]

    default void setIcon(FilePath icon)
    {
        setIcon(icon, () -> {});
    }

    void setIcon(FilePath icon, SimpleCallback callback);
}
```

This interface is in a separate JAR, along with source code. The source code is compiled along with the Android library. I copy the sources in that JAR to the Android library's generated sources folder before compilation.

On Android, I have an implementation of the display device, which just ignores this method. This is only relevant for the desktop and html5 backends of my engine.

``` java
public class AndroidDisplayDevice implements IDisplayDevice
{
    @Override
    public void setIcon(FilePath icon, SimpleCallback callback)
    {
    }
}
```

Now I use this Android library with my application, and I call the `setIcon(FilePath)` method from the instance of `AndroidDisplayDevice`

``` java
IDisplayDevice display = new AndroidDisplayDevice();
display.setIcon(iconFilePath);
```

I assume that this should not do anything, but this is resulting in an `AbstractMethodError` being thrown. If I also call with a callback, this error goes away, but there should not be an error right?

```
FATAL EXCEPTION: GLThread 6297
Process: com.shc.lostorion.android, PID: 26000
java.lang.AbstractMethodError: abstract method "void com.shc.silenceengine.core.IDisplayDevice.setIcon(com.shc.silenceengine.io.FilePath)"
    at com.shc.lostorion.LostOrion.init(LostOrion.java:25)
    at com.shc.silenceengine.backend.android.AndroidRuntime.start(AndroidRuntime.java:88)
    at com.shc.lostorion.android.LostOrionLauncher.launchGame(LostOrionLauncher.java:15)
    at com.shc.silenceengine.backend.android.AndroidLauncher$$Lambda$1.invoke(Unknown Source)
    at com.shc.silenceengine.backend.android.AndroidWindow.onSurfaceCreated(AndroidWindow.java:51)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

I will try to provide an SSCCE after the LudumDare competition that I'm doing right now. Any insights?

**Comment by orfjackal** [comment]
I'm assuming that you have Retrolambda's defaultMethods mode. Since IDisplayDevice and AndroidDisplayDevice are in different modules, Retrolambda will not see AndroidDisplayDevice when it backports the default methods in IDisplayDevice. A workaround is to copy the class files from the library and the application into the same directory, run Retrolambda on them, and then repackage it as a JAR. Can you try if that will solve the problem?
