### ISSUE TITLE
Retrolambda unnable to backport dependencies

### ISSUE THREAD

**Issue by distjoy** [orfjackal/retrolambda#114]
Am running a project that imports selenium (.jar) as an dependency via gradle, selenium was compiled with java8. retrolambda was unnable to backport this dependency. what could be issue? Could it be that retrolambda cant backport dependecies of a project??

**Comment by orfjackal** [comment]
That's right. It won't backport the dependencies. If you really want, you will need to backport each dependency individually, test that they still work (for example they cannot use any Java 8 APIs), and publish the backported binaries somewhere.
