### ISSUE TITLE
dependency questions

### ISSUE THREAD

**Issue by aaltonenzhang** [orfjackal/retrolambda#117]
When using the tool in cmd way, we should provide classpath parameter. What if the dependency class itself need to be translated to java6 grammar first? Should we totally understand the compile chain and compile the files one by one in order.

**Comment by orfjackal** [comment]
You should either first backport every dependency, or combine them into one uberjar and backport it as a whole (Retrolambda doesn't yet support processing JAR files, so you'll need to unpack the JAR to process the .class files it contains).
