### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by cuijianzhi** [orfjackal/retrolambda#125]
java.lang.NoSuchMethodError: No static method com_fosafer_lib_Fosafer$$Lambda$1_lambda$getOkHttpClient$0(Ljava/lang/String;Ljavax/net/ssl/SSLSession;)Z in class Lcom/fosafer/lib/Fosafer; or its super classes (declaration of 'com.fosafer.lib.Fosafer' appears in /data/app/com.fosafer.attendance.test-1/base.apk)

May be the version of the problem, I started with the latest version 3.5.0. In exchange for the previous 3.2.0, the problem is solved.

**Comment by orfjackal** [comment]
Please create a [SSCCE](http://sscce.org/) for reproducing this.

**Comment by cuijianzhi** [comment]
May be the version of the problem, I started with the latest version 3.5.0. In exchange for the previous 3.2.0, the problem is solved.

**Comment by cuijianzhi** [comment]
Hey boy:
today i meet it again.
but this time i fixed i thought by remove the lambda way with normal  code.It work fine.
Before:
`  HostnameVerifier DO_NOT_VERIFY = (hostname,session)->true;`

after :
`  HostnameVerifier DO_NOT_VERIFY = new HostnameVerifier() {
                @Override
                public boolean verify(String hostname, SSLSession session) {
                    return true;
                }
            };`
