### ISSUE TITLE
NPE when used with Pitest

### ISSUE THREAD

**Issue by 8armed-monkey** [orfjackal/retrolambda#131]
The detail of the problem could be found here:
[https://github.com/hcoles/pitest/issues/345](https://github.com/hcoles/pitest/issues/345)

A sample project where the issue occurs could be found here:
[https://github.com/8armed-monkey/sample-npe-pitest-retrolambda](https://github.com/8armed-monkey/sample-npe-pitest-retrolambda)

Class where the lambda is used:
[test.event.EventBroadcasterImpl.java](https://github.com/8armed-monkey/sample-npe-pitest-retrolambda/blob/master/meh/src/main/java/test/event/EventBroadcasterImpl.java)

The NPE doesn't occur if I change the lambda / method reference to anonymous inner classes (the Retrolambda plugin is still being used, but it doesn't create additional classes).

**Comment by orfjackal** [comment]
The ticket hints that this may be related to missing source file debug information. Retrolambda persists the lambda classes that Java 8 generates at runtime, and those classes are missing debug information. It might be possible to add debug information at least for the source file name.

**Comment by orfjackal** [comment]
I wonder if #130 is related.

**Comment by orfjackal** [comment]
This has been fixed in Retrolambda 2.5.3
