### ISSUE TITLE
The Maven plugin no longer uses classpathFile

### ISSUE THREAD

**Issue by dmitri-gb** [orfjackal/retrolambda#141]
The Maven plugin was made to use the `retrolambda.classpathFile` property in commit fd5b63c7745eeaca99b6b8401611e5cd80d1aa25, however, a regression was introduced in c534b941226060e6421a244835e65523ab748795 and the plugin now uses `retrolambda.classpath` again, which makes it fail to execute on Windows when the class path is very long.

**Comment by orfjackal** [comment]
Thanks for finding this. It is fixed in Retrolambda 2.5.4.
