### ISSUE TITLE
FunctionalInterface containing static/default method used from different module (jar)

### ISSUE THREAD

**Issue by mhorejsi** [orfjackal/retrolambda#36]
There seems to be a bug in retrolambda. 

Let's suppose that I have the following interface in file x.jar. This module is successfully complied with retrolambda.
```
@FunctionalInterface
public interface X<T> {
    T accept(T t);
    static <T> X<T> identity() {
        return t -> t;
     } 
}
```

I use this interface from another module - y.jar. This file is also compiled with retrolambda, but unsuccessfully.
```
public class Y {
    Y(){
        X<String> op = X.identity();
        work(t -> t); // this is the problematic line
    }
   void work(X<String> operator) {}
}
```

When a functional interface with a static/default method is used as lambda expression from another module (=jar file), gradle retrolambda plugin throws the following error:
```
Execution failed for task ':Y:compileRetrolambdaMain'.
> Process 'command 'C:\Program Files (x86)\Java\jdk1.8.0_11\bin\java.exe'' finished with non-zero exit value 1
```

If I have both files in the same module, everything works as expected. 

When I remove work(t -> t); from Y, module Y compiles.

I tried retrolambda 1.4.0 and 1.7.0. retrolambda.bytecodeVersion is 52.

**Comment by orfjackal** [comment]
Closing this issue because it's unlikely that there will be a solution for this limitation. https://github.com/orfjackal/retrolambda#known-limitations
