### ISSUE TITLE
Backport Java 7 AutoCloseable

### ISSUE THREAD

**Issue by Alexander--** [orfjackal/retrolambda#39]
I have read [your comment](https://github.com/ReactiveX/RxAndroid/issues/37) at RxAndroid tracker, and here I am. IMO, this would work be best implemented by replacing all AutoCloseable usage with Closeable, I doubt, that there would be any real-live negative consequences from doing so, and methods, relying on receiving Closeable would still work fine.

**Comment by orfjackal** [comment]
I'm closing this issue as unreproducible/"won't fix". Submit a SSCCE of a real use case to reopen.
