### ISSUE TITLE
Verify error with self-referential lambda

### ISSUE THREAD

**Issue by dalewking** [orfjackal/retrolambda#43]
Hesitate to call this a bug but I'll report this here as it took many hours to track down.

We have an interface that contains a static field DEFAULT which is an instance of the interface itself as in:

    public MyInterface
    {
        int foo(int a);

        MyInterface DEFAULT = ...
    }

Originally the value for default was an anoymous inner class as in:

    MyInteface DEFAULT = new MyInterface()
    {
        pubic int foo(int a) { return someCall(a); }
    }

which worked find. After adding retrolambda to the project, Android Studio said we should convert that to a lambda expression like in:

    MyInteface DEFAULT = a -> someCall(a);
 
The result is that this worked on Lollipop, but crashes with a verify error on pre-Lollipop.

Not sure if you can make this work, but if not you could at least fail the build if you detect it.

**Comment by mgrzechocinski** [comment]
Hey, in fact this was an issue and is already fixed in v1.8.1. Take a look at #42

**Comment by dalewking** [comment]
Confirmed that 1.8.1 fixed the issue.
