### ISSUE TITLE
Unnable to call default interface method

### ISSUE THREAD

**Issue by Archinamon** [orfjackal/retrolambda#47]
Getting java.lang.NoSuchMethodError in android runtime when trying to override default interface methods; Without overriding everything works fine;
Tried to override simple method (default void doSmth()) and a generic methods (default ImplType<T> doSmth()).
Using Factory pattern to navigate across the multiple concrete types and call methods casting all of them to interface type. Maybe, if I cast working type to concrete one I won't get this error?
But that's not suites my arch :(

Upd:
Remembered, that you inject default methods into implementators indirectly. Maybe there's a possibility to hold method signature inside interface type like simple non-implemented interface method? My mind this error ucurres when Java tries to access method via interface methods table but this interface doesn't contain any information about default methods anymore.

**Comment by orfjackal** [comment]
Please post an example of code that reproduces this, the full stack trace, build log and the resulting .class files.

**Comment by orfjackal** [comment]
Does this happen only on Android, or also on desktop Java?

**Comment by Archinamon** [comment]
https://www.dropbox.com/s/x07mv4ir4ksuv49/debug.7z?dl=0

Target interface file is — io.db.DictsDbDecorator
Line where I got error — io.FxDictionary:407
The problem is — io.db.impl.UpdateDbAdapter:50

When I change the return type signature to abstract class, that implements this interface, then all going cool.
Desktop java I didn't test, only android.

**Comment by orfjackal** [comment]
The file `DictsDbDecorator.class` still contains the method bodies of the default methods, which means that Retrolambda was executed without enabling the support for default methods. The build log should show Retrolambda printing warnings about it.

Note that the Gradle plugin has not yet been updated to support Retrolambda 2.0.0 (https://github.com/evant/gradle-retrolambda/issues/93), but you should be able to use it by adding `-Dretrolambda.defaultMethods=true` to the plugin's `jvmArgs` and by disabling Gradle's incremental compiler.

**Comment by orfjackal** [comment]
Please leave a comment that whether you are able to make it work or not.

**Comment by Archinamon** [comment]
Thank's! Adding jvmArgs works for me. But still need to test everything around.
