### ISSUE TITLE
retrolambda with Buck build

### ISSUE THREAD

**Issue by giorgio-zamparelli** [orfjackal/retrolambda#50]
Any idea on how to make retrolambda work on Android with Buck build tool made by Facebook?
https://facebook.github.io/buck/

**Comment by orfjackal** [comment]
You can call Retrolambda [as a command line application](https://github.com/orfjackal/retrolambda#command-line-application). As long as Buck has the ability to download JARs from Maven Central and a way to run arbitrary commands, it should be possible.

The other option is to extend Buck to support Retrolambda. That's outside the scope of Retrolambda, but you are welcome to develop your own Buck plugin/rule and publish it. You better ask for help from Buck's discussion group.

**Comment by Piasy** [comment]
@giorgio-zamparelli Hi I have create a demo project that could let BUCK and RetroLambda work together, check it out! https://github.com/Piasy/BuckJava8RetroLambdaDemo
