### ISSUE TITLE
Link to stream backport library

### ISSUE THREAD

**Issue by fschoellhammer** [orfjackal/retrolambda#51]
Hi, I am a great fan of retrolambda and I have been using it for months, thanks so much for this great tool.

Recently I found another interesting library which goes very well with Retrolambda, namely streamsupport, a backport of Java8 stream API (http://sourceforge.net/projects/streamsupport/). I think this might be useful for many users of Retrolambda, and I was wondering if you could add a link to the readme, I think that project would deserve more attention.

Anyway, thanks so much for retrolambda!

**Comment by elliatab** [comment]
Sounds like a good idea as both libraries complement each other.

**Comment by orfjackal** [comment]
Done. I also mention the ThreeTen project there. Are there also others?
