### ISSUE TITLE
NPE when using method reference 

### ISSUE THREAD

**Issue by VasyaFromRussia** [orfjackal/retrolambda#57]
When I use method reference, sometimes I get strange exception. 

This code:
```
 chatController
                .loadMoreMessages()
                .subscribe(view::addItems, e -> Logger.e(TAG, e.getMessage(), e));
```

causes this exception.
```
D/HockeyApp(16936): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
```

When I expand lambdas and create anonymous object, it works with no errors.
```
 chatController
                .loadMoreMessages()
                .subscribe(new Subscriber<List<ServerChatMessage>>() {
                    @Override
                    public void onCompleted() {

                    }

                    @Override
                    public void onError(Throwable e) {
                        Logger.e(TAG, e.getMessage(), e);
                    }

                    @Override
                    public void onNext(List<ServerChatMessage> serverChatMessages) {
                        view.addItems(serverChatMessages);
                    }
                });
```

**Comment by orfjackal** [comment]
Those two code snippets are not equivalent; you would have to pass two anonymous classes to subscribe for it to work the same way as the method references in the first code. Does the code work on Java 8, without Retrolamdba? Also I find it unlikely for Retrolambda to cause such an exception. Please create an [SSCCE](http://sscce.org/) and post the full exception stack trace. As it stands now, I can't reproduce this.
