### ISSUE TITLE
default method found in version 50.0 classfile

### ISSUE THREAD

**Issue by abullon** [orfjackal/retrolambda#58]
Hi 

Im try to use retrorlambda gradle plugin for this proyect 

https://github.com/advantageous/qbit

I began with this config at the top of the buil.gradle file

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        classpath "me.tatarka:gradle-retrolambda:+"
    }
}

//And add the plugin settings for each one of the subproyects
subprojects {
...
project('core') {

    apply plugin: 'me.tatarka.retrolambda'

    dependencies {
        compile "io.advantageous.boon:boon-reflekt:$boonVersion"
        compile "io.advantageous.boon:boon-json:$boonVersion"
        testCompile project(':qbit:test-support')
        retrolambdaConfig 'net.orfjackal.retrolambda:retrolambda:+'
    }
......
}

project('boon') {

    apply plugin: 'me.tatarka.retrolambda'

    dependencies {
        compile project(':qbit:core')
        compile "io.advantageous.boon:boon-json:$boonVersion"
        retrolambdaConfig 'net.orfjackal.retrolambda:retrolambda:+'
        testCompile project(':qbit:test-support')
    }

    ...
}
...
}

When I excecute the "gradle clean installa" command the first proyect compile without problems but then

:qbit:clean UP-TO-DATE
:qbit:boon:clean
:qbit:cluster:clean UP-TO-DATE
:qbit:core:clean
:qbit:test-support:clean UP-TO-DATE
:qbit:web:clean UP-TO-DATE
:qbit:cluster:admin:clean UP-TO-DATE
:qbit:cluster:consul-client:clean UP-TO-DATE
:qbit:cluster:eventbus-replicator:clean UP-TO-DATE
:qbit:web:servlet:clean UP-TO-DATE
:qbit:web:vertx:clean UP-TO-DATE
:qbit:core:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:qbit:core:compileRetrolambdaMain
:qbit:core:processResources UP-TO-DATE
:qbit:core:classes
:qbit:core:jar
:qbit:boon:compileJava
C:\Users\s36248\IdeaProjects\qbit-1-master\qbit\boon\src\main\java\io\advantageous\qbit\boon\BoonQBi
tFactory.java:22: error: cannot access Factory
import io.advantageous.qbit.Factory;
                           ^
  bad class file: C:\Users\s36248\IdeaProjects\qbit-1-master\qbit\core\build\libs\qbit-core-0.8.10-S
NAPSHOT.jar(io/advantageous/qbit/Factory.class)
    default method found in version 50.0 classfile
    Please remove or make sure it appears in the correct subdirectory of the classpath.
:qbit:boon:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qbit:boon:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more l
og output.

BUILD FAILED

Is this a bug? or I'm doing something wrong?

**Comment by orfjackal** [comment]
The backporting of default methods is disabled by default. You will need to configure it to be enabled: https://github.com/evant/gradle-retrolambda#configuration This is because there are some limitations to backporting default methods: https://github.com/orfjackal/retrolambda#known-limitations

**Comment by abullon** [comment]
I put the default methods configuration at subproject level

project('core') {

    apply plugin: 'me.tatarka.retrolambda'

    dependencies {
        compile "io.advantageous.boon:boon-reflekt:$boonVersion"
        compile "io.advantageous.boon:boon-json:$boonVersion"
        testCompile project(':qbit:test-support')
        retrolambdaConfig 'net.orfjackal.retrolambda:retrolambda:+'
    }

    retrolambda {
        defaultMethods true
    }

    ...
}

project('boon') {

    apply plugin: 'me.tatarka.retrolambda'


    dependencies {
        compile project(':qbit:core')
        compile "io.advantageous.boon:boon-json:$boonVersion"
        testCompile project(':qbit:test-support')
    }

    retrolambda {
        defaultMethods true
    }
...
}

But the error is more creepy

:qbit:clean UP-TO-DATE
:qbit:boon:clean
:qbit:cluster:clean UP-TO-DATE
:qbit:core:clean
:qbit:test-support:clean UP-TO-DATE
:qbit:web:clean UP-TO-DATE
:qbit:cluster:admin:clean UP-TO-DATE
:qbit:cluster:consul-client:clean UP-TO-DATE
:qbit:cluster:eventbus-replicator:clean UP-TO-DATE
:qbit:web:servlet:clean UP-TO-DATE
:qbit:web:vertx:clean UP-TO-DATE
:qbit:core:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:qbit:core:compileRetrolambdaMain
:qbit:core:processResources UP-TO-DATE
:qbit:core:classes
:qbit:core:jar
:qbit:boon:compileJava
C:\Users\s36248\IdeaProjects\qbit-1-master\qbit\boon\src\main\java\io\advantageous\qbit\boon\BoonQB
tFactory.java:81: error: BoonQBitFactory is not abstract and does not override abstract method crea
eMethodCallListToBeParsedFromBody(String,Object,Request<Object>) in Factory
public class BoonQBitFactory implements Factory {
       ^
C:\Users\s36248\IdeaProjects\qbit-1-master\qbit\boon\src\main\java\io\advantageous\qbit\boon\BoonQB
tFactory.java:110: error: incompatible types: PeriodicScheduler is not a functional interface
        return (runnable, interval, timeUnit) -> scheduledExecutorService.scheduleAtFixedRate(runna
le, interval, interval, timeUnit);
               ^
    multiple non-overriding abstract methods found in interface PeriodicScheduler
C:\Users\s36248\IdeaProjects\qbit-1-master\qbit\boon\src\main\java\io\advantageous\qbit\events\impl
BoonEventManager.java:53: error: BoonEventManager is not abstract and does not override abstract me
hod joinServices(ServiceQueue...) in EventManager
public class BoonEventManager implements EventManager {
       ^
C:\Users\s36248\IdeaProjects\qbit-1-master\qbit\boon\src\main\java\io\advantageous\qbit\events\impl
BoonEventManager.java:304: error: <anonymous io.advantageous.qbit.events.impl.BoonEventManager$1> i
 not abstract and does not override abstract method subscriber() in EventListener
            this.register(channel, new EventConsumer<Object>() {
                                                               ^
C:\Users\s36248\IdeaProjects\qbit-1-master\qbit\boon\src\main\java\io\advantageous\qbit\events\impl
BoonEventManager.java:313: error: <anonymous io.advantageous.qbit.events.impl.BoonEventManager$2> i
 not abstract and does not override abstract method subscriber() in EventSubscriber
            this.register(channel, new EventSubscriber<Object>() {
                                                                 ^
C:\Users\s36248\IdeaProjects\qbit-1-master\qbit\boon\src\main\java\io\advantageous\qbit\events\impl
BoonEventManager.java:369: error: <anonymous io.advantageous.qbit.events.impl.BoonEventManager$3> i
 not abstract and does not override abstract method subscriber() in EventSubscriber
        eventBus.register(channelName, new EventSubscriber<Object>() {
                                                                     ^
C:\Users\s36248\IdeaProjects\qbit-1-master\qbit\boon\src\main\java\io\advantageous\qbit\events\impl
BoonEventManager.java:385: error: <anonymous io.advantageous.qbit.events.impl.BoonEventManager$4> i
 not abstract and does not override abstract method subscriber() in EventListener
        eventBus.register(channelName, new EventConsumer<Object>() {


But if I just configure the default methods in subproject "project('boon') {}" the error is the same 

C:\Users\s36248\IdeaProjects\qbit-1-master\qbit\boon\src\main\java\io\advantageous\qbit\boon\BoonQBi
tFactory.java:22: error: cannot access Factory
import io.advantageous.qbit.Factory;
^
bad class file: C:\Users\s36248\IdeaProjects\qbit-1-master\qbit\core\build\libs\qbit-core-0.8.10-S
NAPSHOT.jar(io/advantageous/qbit/Factory.class)
default method found in version 50.0 classfile
Please remove or make sure it appears in the correct subdirectory of the classpath.
:qbit:boon:compileJava FAILED

**Comment by orfjackal** [comment]
That's because of Retrolambda's limitations: https://github.com/orfjackal/retrolambda#known-limitations

For example the BoonQBitFactory is in a different module than Factory, so the Java compiler cannot anymore compile it after Retrolambda has backported the default methods in Factory.
