### ISSUE TITLE
Is there a way to make the IDE happy?

### ISSUE THREAD

**Issue by molikto** [orfjackal/retrolambda#59]
Seems the IDE (Android Studio) will randomly change back to language level 6.0, and every time I need to change back manually.

**Comment by orfjackal** [comment]
I don't know about that, because I don't develop for Android. Would @evant know about it?

**Comment by orfjackal** [comment]
Do these instructions help? https://github.com/evant/gradle-retrolambda#android-studio-setup

**Comment by molikto** [comment]
yes. it works. Just want to be sure that it will not break anything?
