### ISSUE TITLE
Would you expect the following code to be optimized to use a singleton stateless lambda?

### ISSUE THREAD

**Issue by epatey** [orfjackal/retrolambda#63]
Thank you for RetroLambda. It's awesome. 

```
Function<String, String> foo1 = (instance) -> instance;
Function<String, String> foo2 = (instance) -> instance;
assert(foo1 == foo2);
```
I ask because in my experimentation, `foo1` is **not** the same instance of `foo2`. Two new lambdas are allocated every time through the code.

**Comment by orfjackal** [comment]
They are not the same instances because they are not the same lambdas. They are two different lambdas, so two instances are created, but each of them only once.

This code demonstrates that for each lambda only one instance is created:

        Function<String, String> foo1 = null;
        for (int i = 0; i < 10; i++) {
            Function<String, String> foo2 = (instance) -> instance;
            if (foo1 != null && foo1 != foo2) {
                throw new AssertionError();
            }
            foo1 = foo2;
        }

**Comment by epatey** [comment]
Ah. I get it. Of course. My test case was bogus. Thanks.

**Comment by mperry** [comment]
@orfjackal Can you explain how retro lambda does this?

**Comment by orfjackal** [comment]
@mperry See the `generateFactoryMethod()` method and the code that calls `isStateless()` in https://github.com/orfjackal/retrolambda/blob/master/retrolambda/src/main/java/net/orfjackal/retrolambda/lambdas/BackportLambdaClass.java
