### ISSUE TITLE
Compilation time has increased ten fold

### ISSUE THREAD

**Issue by v1shnu** [orfjackal/retrolambda#65]
Ever since I updated to `v3.2.2`, compilation has started to take a really long time (10-50x the normal). 
Things are fine in every version upto `v3.0.1`. 
In the latest version, most modules are getting stuck in the `compileReleaseJava` step. 
I'd be happy to provide you more data, please let me know how.

**Comment by orfjackal** [comment]
@evant Can you take a look at this? Looks like a Gradle plugin issue.

**Comment by sandrom** [comment]
i have the same problem. its really annoying unfortunately. crazy build times

**Comment by markmckenna** [comment]
I'll add my voice to this as well.  I'll also make a ticket over at [https://github.com/evant/gradle-retrolambda].

I should add that the massive time increase takes place after `compile*Java` but before `compileRetrolambda*`, and it happens even when both tasks detect as `UP-TO-DATE`.

**Comment by dbachelder** [comment]
I noticed this when I have the android databinding plugin in my project.. removing it seems to take us back to normal. http://stackoverflow.com/questions/32543518/missing-time-in-android-gradle-build-profile

I don't know if it's at all related, but the time also seems to come between tasks..

**Comment by markmckenna** [comment]
I believe I've traced the issue back to this: https://github.com/evant/gradle-retrolambda/issues/108

Looks like the finalizer hook in Gradle takes exponential time to run, so the bigger the project gets, the longer it takes to build.  That makes sense to me as well, because it got abruptly slower as soon as I hooked unit tests up to run during `installDebug`.

**Comment by evant** [comment]
I released a SNAPSHOT that attempts to resolve this (see https://github.com/evant/gradle-retrolambda/issues/108)

@dbachelder fyi the databining plugin has it's own issues. It currently is not incremental at all _and_ will force a complete recompile even if nothing has changed!

**Comment by markmckenna** [comment]
Further update: I find that my problem is successfully addressed by https://github.com/evant/gradle-retrolambda/issues/129.  This moves to a beta/snapshot pairing, so it probably won't be for everyone but I've found it satisfactory so far.

**Comment by dbachelder** [comment]
@evant the snapshot of gradle-retrolambda also fixed the issue that I reported on data binding. everything is nice and snappy now.

**Comment by evant** [comment]
Released `3.2.3` which works around this issue.

**Comment by nevir** [comment]
heads up; it doesn't appear to be pushed to https://plugins.gradle.org/plugin/me.tatarka.retrolambda yet

**Comment by nevir** [comment]
Sorry, wrong repo!
