### ISSUE TITLE
Rewrite generated calls to Objects.requireNonNull()

### ISSUE THREAD

**Issue by cushon** [orfjackal/retrolambda#75]
In JDK 8 and below, javac generates synthetic null-checks by calling `Object.getClass`. Starting in JDK 9, `Objects.requireNonNull()` is used if it is available (see [JDK-8074306](https://bugs.openjdk.java.net/browse/JDK-8074306)).

This prevents retrolambda users from compiling code with JDK9 and running it on JDK6 or below, since `java.util.Objects` was introduced in JDK7.

When targeting JDK < 7, retrolambda should rewrite the generated calls to `requireNonNull`.

**Comment by orfjackal** [comment]
Cool. Thanks about telling what JDK 9 does. I haven't yet tried using it. I'll try to get some time to update Retrolambda this month.

**Comment by orfjackal** [comment]
This is included in Retrolambda 2.2.0
