### ISSUE TITLE
error: incompatible types

### ISSUE THREAD

**Issue by ravikwow** [orfjackal/retrolambda#78]
Work fine
```java
Pair pair = new Pair<>(key, value);
Observable.just(pair)
        .map(this::createPreference)
        .subscribe(new Action1<Preference>() {
            @Override
            public void call(Preference preference) {
                addPreference(preference);
            }
        });
```
error: incompatible types: Object cannot be converted to Preference
```java
Pair pair = new Pair<>(key, value);
Observable.just(pair)
        .map(this::createPreference)
        .subscribe(preference -> {
            addPreference(preference);
        });
```
error: no suitable method found for subscribe(this::addPreference)
method Observable.subscribe(Action1) is not applicable
(argument mismatch; invalid method reference
incompatible types: Object cannot be converted to Preference)
method Observable.subscribe(Observer) is not applicable
(argument mismatch; Observer is not a functional interface
multiple non-overriding abstract methods found in interface Observer)
method Observable.subscribe(Subscriber) is not applicable
(argument mismatch; Subscriber is not a functional interface)
method Observable.<T>subscribe(Subscriber<? super T>,Observable<T>) is not applicable
(cannot infer type-variable(s) T
(actual and formal argument lists differ in length))
where T is a type-variable:
T extends Object declared in method <T>subscribe(Subscriber<? super T>,Observable<T>)
```java
Pair pair = new Pair<>(key, value);
Observable.just(pair)
        .map(this::createPreference)
        .subscribe(this::addPreference);
```
But work fine
```java
Observable.just(new Pair<>(key, value))
        .map(this::createPreference)
        .subscribe(this::addPreference);
```
This is normal?

**Comment by orfjackal** [comment]
What produces those messages? Is it the Java compiler or does Retrolambda throw an exception?

**Comment by ravikwow** [comment]
This is Java compiler

**Comment by ravikwow** [comment]
Sample project https://bitbucket.org/ravikwow/lambdasampleerror

**Comment by orfjackal** [comment]
In that case it's not related to Retrolambda, but is a generic question about Java. You better ask it at http://stackoverflow.com/
