### ISSUE TITLE
GWT?

### ISSUE THREAD

**Issue by Namek** [orfjackal/retrolambda#79]
Google Web Toolkit transpiles Java 6/7 into JavaScript. Since Retrolambda processes only bytecode I can't make it working with GWT. Is there any way to transpile Java 8 code into Java 6 or 7? Possibly after some modification?

**Comment by orfjackal** [comment]
I'm not aware of tools that would backport Java 8 source code. It might be possible to use APT (Annotation Processing Tool) to get access to the AST of the Java 8 source and then convert the lambdas into anonymous classes. APT's capabilities are not documented well, but if you read the source code of https://projectlombok.org/ you can learn what can be done with it. Good luck!

**Comment by orfjackal** [comment]
Or then just wait for GWT to support Java 8. ;) It's mentioned in the release notes for 2.8.0 (Beta1) http://www.gwtproject.org/release-notes.html

**Comment by Namek** [comment]
Thanks!
