### ISSUE TITLE
Execution failed for task ':test'. > When running gradle with java 8, you must set the path to the old jdk

### ISSUE THREAD

**Issue by urosjarc** [orfjackal/retrolambda#80]
Execution failed for task ':test'. > When running gradle with java 8, you must set the path to the old jdk, either with property retrolambda.oldJdk or environment variable JAVA6_HOME/JAVA7_HOME

How can I run my tests without this error.

**Comment by orfjackal** [comment]
The solution is to do what it says in the error message. See the instructions for using the Gradle plugin: https://github.com/evant/gradle-retrolambda#configuration

**Comment by BenedettoDC** [comment]
This hint doesnt help at all.
