### ISSUE TITLE
ClassNotFoundException when using retrolambda.jar at command line.

### ISSUE THREAD

**Issue by perezd** [orfjackal/retrolambda#90]
Here's my stack trace (and runtime output): https://gist.github.com/perezd/f3c98350dba15e975a46
For background, I'm using the following command:

```
/usr/bin/java \
-Dretrolambda.inputDir=/tmp/in_classesdir \
-Dretrolambda.outputDir=/tmp/out_classesdir \
-Dretrolambda.classpathFile=/tmp/classfiles.txt  \
-javaagent:retrolambda-2.1.0.jar  \
-jar retrolambda-2.1.0.jar;
```

Any idea what I'm doing wrong here? Its probably my fault, just not sure what I did wrong.

**Comment by orfjackal** [comment]
The problem is the classpath. Instead of listing all files in it, you must list the directory that contains those files. The `/tmp/classfiles.txt` file should contain just the line `/tmp/in_classesdir` (and paths to the JARs of any third-party libraries).

**Comment by perezd** [comment]
oh shoot. OK I think I see what you mean. Yeah, that wasn't entirely clear from the docs. Will try again. Thanks!

**Comment by perezd** [comment]
I tried what you recommended and that fixed it. THANK YOU! Great project!

**Comment by perezd** [comment]
So, I actually have this classpath problem again, but this time with Android libraries.

I've added this jar to the classpathfile: http://mvnrepository.com/artifact/org.robolectric/android-all/5.1.1_r9-robolectric-1

And I've confirmed that this jar as `android.app.IntentService` but I continue to get this error:

`Caused by: java.lang.ClassNotFoundException: android.app.IntentService`

What can I do to diagnose this further?

**Comment by perezd** [comment]
Does every .class file (of even dependencies) need to be in the inputDir?

**Comment by perezd** [comment]
OK I just answered my own question, it apparently does need them all. Why does classpath exist at all then?

**Comment by perezd** [comment]
Nevermind me, this is a bug with bazel.io's sandboxing compiler. Sorry for the spam!!
