### ISSUE TITLE
Objects.requireNonNull() generated in Java 6 mode

### ISSUE THREAD

**Issue by ben-manes** [orfjackal/retrolambda#92]
For some reason Java 7 method calls are being generated in Java 6 mode. This fails on a [Samsung Galaxy Rugby](http://www.samsung.com/us/mobile/cell-phones/SGH-I547ZKAATT-specs) phone which is Java 6 only. I am using Retrolambda v2.1.0, gradle-retrolambda v3.2.5, and the default (Java 6) configuration. I noticed when upgrading from v3.2.4 (with RL v2.0.6) that the older version generated many more usages of `requireNonNull` for other methods in that class file. I also tried installing JDK6 and setting `JAVA6_HOME` per the plugin, but that had no effect.

```java
@ReactMethod
public void getCurrentPosition(Promise promise) {
  geolocation.getCurrentPosition(new WritableNativeMap(),
      promise::resolve, (any) -> promise.reject(""));
}
```

```java
public void getCurrentPosition(com.facebook.react.bridge.Promise);
  Code:
     0: aload_0
     1: getfield      #38                 // Field geolocation:Lcom/convoy/loaddoc/geolocation/GeolocationReactModule;
     4: new           #73                 // class com/facebook/react/bridge/WritableNativeMap
     7: dup
     8: invokespecial #76                 // Method com/facebook/react/bridge/WritableNativeMap."<init>":()V
    11: aload_1
    12: dup
    13: invokestatic  #268                // Method java/util/Objects.requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;
    16: pop
    17: invokestatic  #274                // Method com/convoy/loaddoc/camera2/view/DocumentCreatorReactModule$$Lambda$1.lambdaFactory$:(Lcom/facebook/react/bridge/Promise;)Lcom/facebook/react/bridge/Callback;
    20: aload_1
    21: invokestatic  #277                // Method com/convoy/loaddoc/camera2/view/DocumentCreatorReactModule$$Lambda$2.lambdaFactory$:(Lcom/facebook/react/bridge/Promise;)Lcom/facebook/react/bridge/Callback;
    24: invokevirtual #280                // Method com/convoy/loaddoc/geolocation/GeolocationReactModule.getCurrentPosition:(Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Callback;Lcom/facebook/react/bridge/Callback;)V
    27: return
```

Do you have any suggestions for resolving this? If not, I'll have to remove retrolambda for the next release, which would be a bummer.

**Comment by JakeWharton** [comment]
Dupe of #75?

**Comment by ben-manes** [comment]
Isn't that one regarding JDK9 behavior and its rewriting behavior? I'm running `oracle64-1.8.0.51`, though perhaps they back ported that change?

**Comment by JakeWharton** [comment]
Perhaps backported, yes. Empirically it seems like the same thing.

**Comment by ben-manes** [comment]
Actually, that leads to an error-prone [bug](https://github.com/google/error-prone/issues/375) which is introduces the `requireNonNull` for target >= 1.7. When I use regular javac the byte code is correct. So it sounds like the resolution is to not use error-prone on Android builds (@cushon).

**Comment by ben-manes** [comment]
Closing as disabling error prone until #75 is resolved.

**Comment by JakeWharton** [comment]
I would call that a temporary workaround, notba resolution. error-prone is
the bees knees!

**Comment by cushon** [comment]
The JDK 9 javac emits requireNonNull for -source >= 7, and Error Prone uses the JDK 9 javac even if it's running on JDK 8.

I opened #93 to fix Retrolambda.
