### ISSUE TITLE
DalvikOverride: Method considered overridden by Dalvik

### ISSUE THREAD

**Issue by orfjackal** [orfjackal/retrolambda#95]
Reported at https://github.com/JakeWharton/retrolambda/issues/3 by @emakar

---

Having lambdas with the same name created in both superclass and its subclass lint would report an error, e.g:

```
com.example.BaseActivity {
  protected onCreate(..) {
    doSmth(() -> {});
  }
}

com.example.details.ChildActivity {
  protected onCreate(..) {
    doSmth(() -> {});
  }
}
```

"ChildActivity: This package private method may be unintentionally overriding lambda$onCreate$0 in com.example.BaseActivity"

**Comment by JakeWharton** [comment]
Thanks for migrating this issue, I was going to ask them to report it upstream anyway. I've disabled issues on my fork which were only there to track issues with the fork itself so the link will now 404.

**Comment by orfjackal** [comment]
This is a duplicate of #109
