### ISSUE TITLE
Retrolambda throws NoSuchMethodException when it clearly exists

### ISSUE THREAD

**Issue by jacks50** [orfjackal/retrolambda#97]
I have this weird issue after updating the jdk to 8u91. Everything was running fine until I got this [error ](http://stackoverflow.com/questions/37567804/javafx-gluon-nosuchmethod-exception-when-it-clearly-exists)(I'm the original poster). Then, by trying to update the JDK, the retrolambda api and also the Gluon api, I can't even start my app without any reason. The whole stacktrace is [here](http://paste.ubuntu.com/16920290/).

**Comment by Jacks50** [comment]
If at least it was possible to see clearly what's causing the error (where and how) it could help a lot. The function it refers to (Main.checkLicence()) is a simple function without parameters, so no lambda, no reference, nothing that could be from Java 8.

**Comment by orfjackal** [comment]
No idea what it could be. If you can produce [a minimal example for reproducing it](http://sscce.org/), that would be helpful.
