### ISSUE TITLE
Android N 

### ISSUE THREAD

**Issue by kotya341** [orfjackal/retrolambda#99]
I am thinking about adding lambas to my project
and I know that android N will support this feature with `jack` in a while
So my question is : is there any reason to implement retrolamba or wait till android N will re released ?

**Comment by orfjackal** [comment]
If you would like to use them already now, instead of waiting for Android N, then that would be one reason. Another reason would be if your application needs to run on previous versions of Android.

**Comment by JakeWharton** [comment]
The Jack toolchain backports the lambdas just like RL. It doesn't support
default/statics or try-with-resources though.

**Comment by zergtmn** [comment]
Also according to my tests Jack is currently 1.5x-2x slower than javac + dx + retrolambda.

**Comment by FabianTerhorst** [comment]
@JakeWharton i always thought try-with-resources isn´t supported on android, even with retrolambda, because android studio is marking the try-with-resources as an error when typing.

**Comment by JakeWharton** [comment]
It works fine. You can disable that with a lint.xml config.

**Comment by JakeWharton** [comment]
`lint.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<lint>
  <issue id="NewApi">
    <ignore regexp="Try-with-resources requires API level 19"/>
  </issue>
</lint>
```
`build.gradle`:
```groovy
android {
  lintOptions {
    lintConfig file('lint.xml')
  }
}
```

**Comment by FabianTerhorst** [comment]
@JakeWharton thanks.

**Comment by caarmen** [comment]
As of today, data binding is not supported if you use jack.  No idea when it will be supported. That could be a reason to stick with retrolambda for now.

**Comment by FabianTerhorst** [comment]
AS 2.3 adds limited Support for databinding with jack

**Comment by BoD** [comment]
@FabianTerhorst I'm sorry to ask but I can't seem to find any reference to AS 2.3 anywhere, 2.2RC being the latest on the Canary channel AFAICT.  Ideas?
